version: "3.8"

services:
#  auction_api_backend:
#    container_name: auction_api_dev
#    image: "mcr.microsoft.com/dotnet/sdk:5.0"
#    volumes:
#      - ./:/app
#    command: dotnet watch --project ./Api run --urls "http://0.0.0.0:80"    
#    ports:
#      - "8081:80" 
    
  auction_api_postgres:
    container_name: auction_bd_dev
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction
      
  elasticsearch:
    container_name: auction_elasticsearch_dev
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - node.name=auction-api-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - auction_api_postgres

  kibana:
    container_name: auction_kibana_dev
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      
volumes:
  es-data:
    driver: local