version: "3"

services:
#  auction_api_backend:
#    container_name: auction_api_dev
#    image: "mcr.microsoft.com/dotnet/sdk:5.0"
#    volumes:
#      - ./:/app
#    command: dotnet watch --project ./Api run --urls "http://0.0.0.0:80"    
#    ports:
#      - "8081:80" 
    
  auction_api_postgres:
    container_name: auction_bd_dev
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres